### ISSUE TITLE
add new validation: `repos/archive` contains no files

### ISSUE THREAD

**Issue by MarcoIeni** [rust-lang/team#1528]
Discussed in https://github.com/rust-lang/team/pull/1527#issuecomment-2299544482

I think there are two ways of doing this:
- add the repo path to the struct [Repo](https://github.com/rust-lang/team/blob/28b7986ab26597b953114596f2190654fecc422b/src/schema.rs#L749) contained in the struct [Data](https://github.com/rust-lang/team/blob/f8c062977dffef820a0b3afbdc1ec524b37c594b/src/data.rs). In this way we can easily validate that the path is not under repos/archive in the check added in https://github.com/rust-lang/team/pull/1527
- edit the [load](https://github.com/rust-lang/team/blob/28b7986ab26597b953114596f2190654fecc422b/src/data.rs#L59) function and check that all entries of the `archive` directory aren't files.

I prefer option 1 because it's cleaner and doesn't complicate the "load" method. What do you think?

Unfortunately we can't edit the closure that we pass to `load_dir` because it only runs on repos under the subdirectories of `archive`, e.g. `repos/archive/rust-lang`.

**Comment by Kobzol** [comment]
I was hoping that we could just modify the existing validations, but I see that they work on `Data`, which doesn't know about the filesystem anymore. I don't like option 1), because it would introduce an external information (filesystem path) into the `Data` world, which otherwise doesn't deal with the filesystem.

But I also don't think that we need to modify the `load` closure. Instead, we could just return an error [here](https://github.com/rust-lang/team/blob/28b7986ab26597b953114596f2190654fecc422b/src/data.rs#L50).

**Comment by MarcoIeni** [comment]
Great suggestion! done https://github.com/rust-lang/team/pull/1530
